import type { ModuleManifest } from "../manifest";

export const academyManifest: ModuleManifest = {
  moduleName: "academy",
  entities: ["Person", "Notification", "AuditLog"],
  databaseTables: [
    "academy_programs",
    "academy_program_translations",
    "academy_courses",
    "academy_course_translations",
    "academy_modules",
    "academy_module_translations",
    "academy_lessons",
    "academy_lesson_translations",
    "academy_resources",
    "academy_instructors",
    "academy_course_instructors",
    "academy_cohorts",
    "academy_enrollment_applications",
    "academy_invitations",
    "academy_enrollments",
    "academy_lesson_progress",
    "academy_assessments",
    "academy_assessment_translations",
    "academy_assessment_submissions",
    "academy_certificates",
  ],
  apiRoutes: [
    "/api/academy/catalog",
    "/api/academy/enrollments",
    "/api/academy/progress",
    "/api/academy/assessments/:assessmentId/submissions",
    "/api/academy/certificates/:verificationId",
    "/api/academy/operations/courses",
    "/api/academy/operations/courses/:courseId",
    "/api/academy/operations/courses/:courseId/workflow",
    "/api/academy/operations/programs",
    "/api/academy/operations/programs/:programId/workflow",
    "/api/academy/operations/invitations",
    "/api/academy/operations/instructors",
    "/api/academy/operations/enrollment-applications/:applicationId",
    "/api/academy/operations/assessments/:submissionId/review",
    "/api/academy/operations/enrollments/:enrollmentId/certificate",
  ],
  dashboardContribution: "academy-learning",
  aiLayerCapabilities: [],
};
