#!/usr/bin/env node
// Executable Documentation Review Pipeline - Broken Link Detection skill.
// See brain/AI/EAO_EXECUTION_PIPELINES.md #3 and brain/AI/EAO_SKILL_LIBRARY.md
// (Documentation Skills -> Broken Link Detection).
// Read-only: only reads files under docs/, brain/, architecture/; writes nothing.
//
// Scope note (explicit, not silently omitted): checks Markdown link syntax
// [text](path) against relative repo paths only. Does not check backtick-quoted
// path mentions (e.g. `brain/AI/EAO_ARCHITECTURE.md` in prose) - those are
// ambiguous with code/variable names and are a future extension, flagged here
// rather than guessed at.
//
// Exports computeBrokenLinks() so other pipelines (Project Health) can
// compose this pipeline's result directly instead of re-deriving it.

import path from "node:path";
import fs from "node:fs";
import { pathToFileURL } from "node:url";
import { findMarkdownFiles, forEachLine } from "./lib/markdown.mjs";

export function computeBrokenLinks(root = process.cwd()) {
  const linkPattern = /\[([^\]]*)\]\(([^)]+)\)/g;
  const files = findMarkdownFiles(root);
  const broken = [];

  for (const file of files) {
    forEachLine(file, (lineText, lineNum) => {
      let match;
      linkPattern.lastIndex = 0;
      while ((match = linkPattern.exec(lineText)) !== null) {
        const target = match[2].trim();
        if (
          /^https?:\/\//.test(target) ||
          /^mailto:/.test(target) ||
          target.startsWith("#") ||
          target === ""
        ) {
          continue; // external, anchor-only, or empty - not a repo file reference
        }
        const [targetPath] = target.split("#"); // strip any trailing #anchor
        const resolved = path.isAbsolute(targetPath)
          ? path.join(root, targetPath)
          : path.resolve(path.dirname(file), targetPath);
        if (!fs.existsSync(resolved)) {
          broken.push({ file: path.relative(root, file), line: lineNum, target });
        }
      }
    });
  }

  return { schemaVersion: 1, filesScanned: files.length, broken };
}

export function renderBrokenLinksMarkdown(result) {
  const { filesScanned, broken } = result;
  const lines = [];
  lines.push("## Documentation Health Report — Broken Link Detection");
  lines.push("");
  lines.push("_Generated by scripts/eao/broken-links.mjs - EAO_EXECUTION_PIPELINES.md #3_");
  lines.push("");
  lines.push(`**Files scanned:** ${filesScanned} (under docs/, brain/, architecture/)`);
  lines.push(`**Broken links found:** ${broken.length}`);
  lines.push("");
  lines.push(broken.length ? broken.map((b) => `- \`${b.file}:${b.line}\` -> \`${b.target}\``).join("\n") : "- none");
  lines.push("");
  lines.push(
    "**Known limitation, disclosed:** backtick-quoted path mentions in prose " +
      "(not Markdown link syntax) are not checked by this run - a separate, " +
      "future extension, not silently included or assumed clean."
  );
  return lines.join("\n");
}

const isMain = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) {
  console.log(renderBrokenLinksMarkdown(computeBrokenLinks()));
}
