#!/usr/bin/env node
// Executable Repository Health Pipeline (EAO, ADR-024) - see
// brain/AI/EAO_EXECUTION_PIPELINES.md #1 and brain/AI/EAO_REPORTING_TEMPLATES.md #1.
// Read-only: runs only inspection git commands, writes nothing, modifies nothing.
//
// Exports computeRepositoryHealth() so other pipelines (Project Health) can
// compose this pipeline's result directly instead of re-deriving it.

import { pathToFileURL } from "node:url";
import {
  getBranch,
  getAheadBehind,
  getStatusPorcelain,
  parseStatus,
  getRecentLog,
} from "./lib/git.mjs";

export function computeRepositoryHealth() {
  const branch = getBranch();
  const aheadBehind = getAheadBehind();
  const { staged, unstaged, untracked } = parseStatus(getStatusPorcelain());
  const log = getRecentLog(10);
  return { schemaVersion: 1, branch, aheadBehind, staged, unstaged, untracked, log };
}

export function renderRepositoryHealthMarkdown(result) {
  const { branch, aheadBehind, staged, unstaged, untracked, log } = result;
  const lines = [];
  lines.push("## Repository Status Report");
  lines.push("");
  lines.push("_Generated by scripts/eao/repository-health.mjs - EAO_EXECUTION_PIPELINES.md #1_");
  lines.push("");
  lines.push(`**Branch:** \`${branch}\``);
  lines.push(`**Remote sync:** ${aheadBehind}`);
  lines.push("");
  lines.push(`**Staged (${staged.length}):**`);
  lines.push(staged.length ? staged.map((l) => `- \`${l}\``).join("\n") : "- none");
  lines.push("");
  lines.push(`**Unstaged (${unstaged.length}):**`);
  lines.push(unstaged.length ? unstaged.map((l) => `- \`${l}\``).join("\n") : "- none");
  lines.push("");
  lines.push(`**Untracked (${untracked.length}):**`);
  lines.push(untracked.length ? untracked.map((l) => `- \`${l}\``).join("\n") : "- none");
  lines.push("");
  lines.push("**Last 10 commits:**");
  lines.push(log.length ? log.map((l) => `- ${l}`).join("\n") : "- none");
  lines.push("");
  return lines.join("\n");
}

const isMain = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) {
  console.log(renderRepositoryHealthMarkdown(computeRepositoryHealth()));
}
