#!/usr/bin/env node
// Executable Repository Health Pipeline (EAO, ADR-024) - see
// brain/AI/EAO_EXECUTION_PIPELINES.md #1 and brain/AI/EAO_REPORTING_TEMPLATES.md #1.
// Read-only: runs only inspection git commands, writes nothing, modifies nothing.

import {
  getBranch,
  getAheadBehind,
  getStatusPorcelain,
  parseStatus,
  getRecentLog,
} from "./lib/git.mjs";

const branch = getBranch();
const aheadBehind = getAheadBehind();
const { staged, unstaged, untracked } = parseStatus(getStatusPorcelain());
const log = getRecentLog(10);

const lines = [];
lines.push("## Repository Status Report");
lines.push("");
lines.push("_Generated by scripts/eao/repository-health.mjs - EAO_EXECUTION_PIPELINES.md #1_");
lines.push("");
lines.push(`**Branch:** \`${branch}\``);
lines.push(`**Remote sync:** ${aheadBehind}`);
lines.push("");
lines.push(`**Staged (${staged.length}):**`);
lines.push(staged.length ? staged.map((l) => `- \`${l}\``).join("\n") : "- none");
lines.push("");
lines.push(`**Unstaged (${unstaged.length}):**`);
lines.push(unstaged.length ? unstaged.map((l) => `- \`${l}\``).join("\n") : "- none");
lines.push("");
lines.push(`**Untracked (${untracked.length}):**`);
lines.push(untracked.length ? untracked.map((l) => `- \`${l}\``).join("\n") : "- none");
lines.push("");
lines.push("**Last 10 commits:**");
lines.push(log.length ? log.map((l) => `- ${l}`).join("\n") : "- none");
lines.push("");

console.log(lines.join("\n"));
