#!/usr/bin/env node
// Executable Knowledge Skill - Terminology Drift Detection.
// See brain/AI/EAO_SKILL_LIBRARY.md (Knowledge Skills -> Terminology Drift
// Detection). Validates that a retired term hasn't silently crept back in
// as a live reference, while not flagging legitimate distinct concepts or
// intentional historical/disclaimer mentions.
//
// Retired-terms registry (small, explicit - not guessed at):
//   "Validation Framework" was retired as an alias for Scientific Review
//   this session, replaced by "Scientific Review Governance Gate" (external)
//   / "Scientific Review Decision Gate" (internal). The distinct, still-valid
//   "Basic Validation Framework" concept is excluded by design.
//
// Read-only.

import path from "node:path";
import { findMarkdownFiles, forEachLine } from "./lib/markdown.mjs";

const RETIRED_TERMS = [
  {
    term: "Validation Framework",
    excludePrefix: "Basic ",
    historicalKeywords: ["retir", "supersed", "historical", "former", "previous", "reconcil"],
    replacement: "Scientific Review Governance Gate / Scientific Review Decision Gate",
  },
];

const root = process.cwd();
const files = findMarkdownFiles(root);

const liveDrift = [];
const disclosedHistorical = [];

for (const { term, excludePrefix, historicalKeywords, replacement } of RETIRED_TERMS) {
  const pattern = new RegExp(`(?<!${excludePrefix})\\b${term}\\b`, "g");
  for (const file of files) {
    forEachLine(file, (lineText, lineNum) => {
      pattern.lastIndex = 0;
      if (!pattern.test(lineText)) return;
      const isHistorical = historicalKeywords.some((kw) =>
        lineText.toLowerCase().includes(kw)
      );
      const entry = {
        file: path.relative(root, file),
        line: lineNum,
        term,
        replacement,
        text: lineText.trim().slice(0, 140),
      };
      if (isHistorical) {
        disclosedHistorical.push(entry);
      } else {
        liveDrift.push(entry);
      }
    });
  }
}

console.log("## Terminology Drift Detection Report");
console.log("");
console.log(
  "_Generated by scripts/eao/terminology-drift.mjs - EAO_SKILL_LIBRARY.md (Knowledge Skills)_"
);
console.log("");
console.log(`**Files scanned:** ${files.length}`);
console.log(`**Retired terms checked:** ${RETIRED_TERMS.map((t) => `"${t.term}"`).join(", ")}`);
console.log("");
console.log(`**Live drift (flagged, needs review) — ${liveDrift.length}:**`);
console.log(
  liveDrift.length
    ? liveDrift.map((e) => `- \`${e.file}:${e.line}\` -> replace with ${e.replacement}`).join("\n")
    : "- none"
);
console.log("");
console.log(`**Disclosed historical mentions (not flagged) — ${disclosedHistorical.length}:**`);
console.log(
  disclosedHistorical.length
    ? disclosedHistorical.map((e) => `- \`${e.file}:${e.line}\``).join("\n")
    : "- none"
);
