import type { ModuleManifest } from "../manifest";

export const membershipManifest: ModuleManifest = {
  moduleName: "membership",
  entities: ["Person", "Payment", "Organization"],
  databaseTables: [
    "members",
    "status_changes",
    "recurring_pledges",
    "institutional_supporter_profiles",
    "membership_benefit_grants",
    "membership_applications",
    "document_acknowledgements",
    "research_participation_preferences",
    "project_research_consents",
    "project_eligibility_records",
    "research_wallets",
    "research_wallet_device_bindings",
    "research_wallet_activation_records",
    "research_credential_issuance_challenges",
    "research_wallet_recovery_challenges",
    "research_wallet_recovery_events",
  ],
  apiRoutes: [
    "/api/membership/create",
    "/api/membership/applications",
    "/api/membership/applications/:applicationId/decision",
    "/api/research/wallet/activate",
    "/api/research/wallet/credentials/challenge",
    "/api/research/wallet/credentials/issue",
    "/api/research/wallet/recover/challenge",
    "/api/research/wallet/recover",
    "/api/research/wallet/revoke",
    "/api/research/verifier/challenge",
    "/api/research/verifier/present",
    "/api/research/verifier/contributions",
    "/api/research/synthetic-smoke",
    "/api/membership/pledge",
    "/api/membership/status",
    "/api/membership/tiers",
    "/api/membership/renewal",
  ],
  dashboardContribution: "membership-summary",
  aiLayerCapabilities: [],
};
